CREATE TABLE bids (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(256) NOT NULL,
  bid_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  product_id INTEGER NOT NULL
);
